package com.ludo.game

class Constants {
    companion object{
    val VICTORY_MESSAGE = "VICTORY"

    val SPACES_NEEDED_TO_GO_HOME = 24
    val HOME_TOTAL_FIELDS = 2

    val ROLLED_VALUE_TO_SPAWN_TOKEN = 6
    val MAX_NUM_OF_ROLLED_DICES = 3
    val SECONDS_FOR_NEXT_ROLL = 1.0f

    val NUM_OF_PLAYERS = 4

    val BACKGROUND_COLOR_R = 0.98039216f
    val BACKGROUND_COLOR_G = 0.86666667f
    val BACKGROUND_COLOR_B = 0.70588235f

    val RED_PLAYER_INDEX = 1
    val BACKGROUND_RED_PLAYER_COLOR_R = 1.0f
    val BACKGROUND_RED_PLAYER_COLOR_G = 0.57647059f
    val BACKGROUND_RED_PLAYER_COLOR_B = 0.50980392f

    val BLUE_PLAYER_INDEX = 2
    val BACKGROUND_BLUE_PLAYER_COLOR_R = 0.50196078f
    val BACKGROUND_BLUE_PLAYER_COLOR_G = 0.6f
    val BACKGROUND_BLUE_PLAYER_COLOR_B = 1.0f

    val GREEN_PLAYER_INDEX = 3
    val BACKGROUND_GREEN_PLAYER_COLOR_R = 0.43921569f
    val BACKGROUND_GREEN_PLAYER_COLOR_G = 0.85882353f
    val BACKGROUND_GREEN_PLAYER_COLOR_B = 0.43921569f

    val YELLOW_PLAYER_INDEX = 0
    val BACKGROUND_YELLOW_PLAYER_COLOR_R = 1.0f
    val BACKGROUND_YELLOW_PLAYER_COLOR_G = 0.99215686f
    val BACKGROUND_YELLOW_PLAYER_COLOR_B = 0.50980392f

    val BACKGROUND_IMAGE_WIDTH = 768
    val BACKGROUND_IMAGE_HEIGHT = 768

    val BOARD_GRID_ROWS = 7
    val BOARD_GRID_COLUMNS = 7
    val BOARD_GRID_SIZE = 96f

    val LUDO_BOARD_JSON_LEVEL = "Ludo_Board.json"
    val LUDO_BOARD_JSON_LEVEL_ARRAY_KEY = "board"
    val LUDO_BOARD_NEXT_UP_TOKEN = 1
    val LUDO_BOARD_NEXT_DOWN_TOKEN = 2
    val LUDO_BOARD_NEXT_LEFT_TOKEN = 3
    val LUDO_BOARD_NEXT_RIGHT_TOKEN = 4
    val LUDO_BOARD_NEXT_NULL_TOKEN = 0
    val LUDO_BOARD_BLUE_HOME = 5
    val LUDO_BOARD_YELLOW_HOME = 6
    val LUDO_BOARD_RED_HOME = 7
    val LUDO_BOARD_GREEN_HOME = 8

    val START_FIELD_GRID_ROWS = 3
    val START_FIELD_GRID_COLUMNS = 3
    val START_FIELD_LOCATION_NUMBER = 2
    val START_FIELD_GRID_SIZE = 64f

     val TOKEN_SELECTABLE_ALPHA = 0.6f
    val TOKEN_NOT_SELECTABLE_ALPHA = 1.0f

    val DICE_TEXT_SCALE = 5}
}